# Generated by Django 2.2.1 on 2019-06-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0002_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='chi_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
