# Generated by Django 2.2.1 on 2019-06-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0004_auto_20190625_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
