# Generated by Django 2.2.1 on 2019-07-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0005_auto_20190625_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='en_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_id',
            field=models.IntegerField(null=True),
        ),
    ]
