# Generated by Django 2.2.1 on 2019-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0007_auto_20190704_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_id',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
