# Generated by Django 2.2.1 on 2019-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0008_auto_20190704_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_id',
            field=models.PositiveIntegerField(max_length=40, null=True),
        ),
    ]
